name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.16.2
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ">=1.12.13"

dependencies:
  # Use these deps for local development
  audio_service_platform_interface:
    # for local use:
    # path: ../audio_service_platform_interface
    git:
      url: https://github.com/NonGrate/ng_audio_service.git
      ref: c377b6564eabe2253a9800c0a34c140c25ac777c
      path: audio_service_platform_interface
  audio_service_web:
    # for local use:
    # path: ../audio_service_web
    git:
      url: https://github.com/NonGrate/ng_audio_service.git
      ref: c377b6564eabe2253a9800c0a34c140c25ac777c
      path: audio_service_web

  # Use these deps when pushing to origin (for the benefit of testers)
#  audio_service_platform_interface:
#    git:
#      url: https://github.com/ryanheise/audio_service.git
#      ref: one-isolate
#      path: audio_service_platform_interface
#  audio_service_web:
#    git:
#      url: https://github.com/ryanheise/audio_service.git
#      ref: one-isolate
#      path: audio_service_web

  # Use these deps when publishing.
  # audio_service_platform_interface: ^1.0.0
  # audio_service_web: ^0.0.1

  audio_session: ^0.0.11
  rxdart: 0.24.1
  flutter_cache_manager: 1.4.2
  js: ^0.6.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dependency_overrides:
  audio_session: ^0.0.11
  rxdart: 0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audioservice
        pluginClass: AudioServicePlugin
      ios:
        pluginClass: AudioServicePlugin
      macos:
        pluginClass: AudioServicePlugin
      web:
        default_package: audio_service_web
