name: audio_service_web
description: Web platform implementation of audio_service. This implementation is endorsed and therefore doesn't require a direct dependency.
version: 0.16.2
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.12.13"

dependencies:
  # Use these deps for local development
  audio_service_platform_interface:
    # For local use:
    # path: ../audio_service_platform_interface
    git:
      url: https://github.com/NonGrate/ng_audio_service.git
      ref: c377b6564eabe2253a9800c0a34c140c25ac777c
      path: audio_service_platform_interface


  # Use these deps when pushing to origin (for the benefit of testers)
#  audio_service_platform_interface:
#    git:
#      url: https://github.com/ryanheise/audio_service.git
#      ref: one-isolate
#      path: audio_service_platform_interface

  # Use these deps when publishing.
  # audio_service_platform_interface: ^1.0.0

  rxdart: ^0.24.1
  js: ^0.6.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AudioServiceWeb
        fileName: audio_service_web.dart
